elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/*.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
    - "9995:9995/udp"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
