elasticsearch:
  restart: always
  build: elasticsearch/
  ports:
    - "9200:9200"
redis:
  image: redis
  restart: always
  ports:
    - "6379:6379"
rsyslog: 
  build: rsyslog/
  restart: always
  volumes: 
     - ./rsyslog/logstore:/var/log/rsyslog
  ports:
     - "514/tcp:514/tcp"
     - "514/udp:514/udp"
  links:
     - redis
kibana:
  build: kibana/
  restart: always
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
logstash:
  build: logstash/
  restart: always
  command: logstash -f /etc/logstash/conf.d/*.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  links:
    - elasticsearch
    - redis
  ports:
    - "55514/udp:55514/udp"
    - "9995:9995/udp"
    - "31311:31311/tcp"
