redis:
  image: redis
  restart: always
rsyslog: 
  build: rsyslog/
  restart: always
  ports:
     - "514/tcp:514/tcp"
     - "514/udp:514/udp"
  links:
     - elasticsearch
     - logstash
elasticsearch:
  restart: always
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  build: logstash/
  restart: always
  command: logstash -f /etc/logstash/conf.d/*.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  links:
    - elasticsearch
    - redis
kibana:
  build: kibana/
  restart: always
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
